/* eslint-disable */
const pokemons = [
	{
		'abilities': '[\'Overgrow\', \'Chlorophyll\']',
		'hp': 45,
		'name': 'Bulbasaur',
		'pokedex_number': 1,
		'sp_attack': 65,
		'sp_defense': 65,
		'speed': 45,
		'type1': 'grass',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Overgrow\', \'Chlorophyll\']',
		'hp': 60,
		'name': 'Ivysaur',
		'pokedex_number': 2,
		'sp_attack': 80,
		'sp_defense': 80,
		'speed': 60,
		'type1': 'grass',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Overgrow\', \'Chlorophyll\']',
		'hp': 80,
		'name': 'Venusaur',
		'pokedex_number': 3,
		'sp_attack': 122,
		'sp_defense': 120,
		'speed': 80,
		'type1': 'grass',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Blaze\', \'Solar Power\']',
		'hp': 39,
		'name': 'Charmander',
		'pokedex_number': 4,
		'sp_attack': 60,
		'sp_defense': 50,
		'speed': 65,
		'type1': 'fire',
		'type2': ''
	},
	{
		'abilities': '[\'Blaze\', \'Solar Power\']',
		'hp': 58,
		'name': 'Charmeleon',
		'pokedex_number': 5,
		'sp_attack': 80,
		'sp_defense': 65,
		'speed': 80,
		'type1': 'fire',
		'type2': ''
	},
	{
		'abilities': '[\'Blaze\', \'Solar Power\']',
		'hp': 78,
		'name': 'Charizard',
		'pokedex_number': 6,
		'sp_attack': 159,
		'sp_defense': 115,
		'speed': 100,
		'type1': 'fire',
		'type2': 'flying'
	},
	{
		'abilities': '[\'Torrent\', \'Rain Dish\']',
		'hp': 44,
		'name': 'Squirtle',
		'pokedex_number': 7,
		'sp_attack': 50,
		'sp_defense': 64,
		'speed': 43,
		'type1': 'water',
		'type2': ''
	},
	{
		'abilities': '[\'Torrent\', \'Rain Dish\']',
		'hp': 59,
		'name': 'Wartortle',
		'pokedex_number': 8,
		'sp_attack': 65,
		'sp_defense': 80,
		'speed': 58,
		'type1': 'water',
		'type2': ''
	},
	{
		'abilities': '[\'Torrent\', \'Rain Dish\']',
		'hp': 79,
		'name': 'Blastoise',
		'pokedex_number': 9,
		'sp_attack': 135,
		'sp_defense': 115,
		'speed': 78,
		'type1': 'water',
		'type2': ''
	},
	{
		'abilities': '[\'Shield Dust\', \'Run Away\']',
		'hp': 45,
		'name': 'Caterpie',
		'pokedex_number': 10,
		'sp_attack': 20,
		'sp_defense': 20,
		'speed': 45,
		'type1': 'bug',
		'type2': ''
	},
	{
		'abilities': '[\'Shed Skin\']',
		'hp': 50,
		'name': 'Metapod',
		'pokedex_number': 11,
		'sp_attack': 25,
		'sp_defense': 25,
		'speed': 30,
		'type1': 'bug',
		'type2': ''
	},
	{
		'abilities': '[\'Compoundeyes\', \'Tinted Lens\']',
		'hp': 60,
		'name': 'Butterfree',
		'pokedex_number': 12,
		'sp_attack': 90,
		'sp_defense': 80,
		'speed': 70,
		'type1': 'bug',
		'type2': 'flying'
	},
	{
		'abilities': '[\'Shield Dust\', \'Run Away\']',
		'hp': 40,
		'name': 'Weedle',
		'pokedex_number': 13,
		'sp_attack': 20,
		'sp_defense': 20,
		'speed': 50,
		'type1': 'bug',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Shed Skin\']',
		'hp': 45,
		'name': 'Kakuna',
		'pokedex_number': 14,
		'sp_attack': 25,
		'sp_defense': 25,
		'speed': 35,
		'type1': 'bug',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Swarm\', \'Sniper\']',
		'hp': 65,
		'name': 'Beedrill',
		'pokedex_number': 15,
		'sp_attack': 15,
		'sp_defense': 80,
		'speed': 145,
		'type1': 'bug',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Keen Eye\', \'Tangled Feet\', \'Big Pecks\']',
		'hp': 40,
		'name': 'Pidgey',
		'pokedex_number': 16,
		'sp_attack': 35,
		'sp_defense': 35,
		'speed': 56,
		'type1': 'normal',
		'type2': 'flying'
	},
	{
		'abilities': '[\'Keen Eye\', \'Tangled Feet\', \'Big Pecks\']',
		'hp': 63,
		'name': 'Pidgeotto',
		'pokedex_number': 17,
		'sp_attack': 50,
		'sp_defense': 50,
		'speed': 71,
		'type1': 'normal',
		'type2': 'flying'
	},
	{
		'abilities': '[\'Keen Eye\', \'Tangled Feet\', \'Big Pecks\']',
		'hp': 83,
		'name': 'Pidgeot',
		'pokedex_number': 18,
		'sp_attack': 135,
		'sp_defense': 80,
		'speed': 121,
		'type1': 'normal',
		'type2': 'flying'
	},
	{
		'abilities': '[\'Run Away\', \'Guts\', \'Hustle\', \'Gluttony\', \'Hustle\', \'Thick Fat\']',
		'hp': 30,
		'name': 'Rattata',
		'pokedex_number': 19,
		'sp_attack': 25,
		'sp_defense': 35,
		'speed': 72,
		'type1': 'normal',
		'type2': 'dark'
	},
	{
		'abilities': '[\'Run Away\', \'Guts\', \'Hustle\', \'Gluttony\', \'Hustle\', \'Thick Fat\']',
		'hp': 75,
		'name': 'Raticate',
		'pokedex_number': 20,
		'sp_attack': 40,
		'sp_defense': 80,
		'speed': 77,
		'type1': 'normal',
		'type2': 'dark'
	},
	{
		'abilities': '[\'Keen Eye\', \'Sniper\']',
		'hp': 40,
		'name': 'Spearow',
		'pokedex_number': 21,
		'sp_attack': 31,
		'sp_defense': 31,
		'speed': 70,
		'type1': 'normal',
		'type2': 'flying'
	},
	{
		'abilities': '[\'Keen Eye\', \'Sniper\']',
		'hp': 65,
		'name': 'Fearow',
		'pokedex_number': 22,
		'sp_attack': 61,
		'sp_defense': 61,
		'speed': 100,
		'type1': 'normal',
		'type2': 'flying'
	},
	{
		'abilities': '[\'Intimidate\', \'Shed Skin\', \'Unnerve\']',
		'hp': 35,
		'name': 'Ekans',
		'pokedex_number': 23,
		'sp_attack': 40,
		'sp_defense': 54,
		'speed': 55,
		'type1': 'poison',
		'type2': ''
	},
	{
		'abilities': '[\'Intimidate\', \'Shed Skin\', \'Unnerve\']',
		'hp': 60,
		'name': 'Arbok',
		'pokedex_number': 24,
		'sp_attack': 65,
		'sp_defense': 79,
		'speed': 80,
		'type1': 'poison',
		'type2': ''
	},
	{
		'abilities': '[\'Static\', \'Lightningrod\']',
		'hp': 35,
		'name': 'Pikachu',
		'pokedex_number': 25,
		'sp_attack': 50,
		'sp_defense': 50,
		'speed': 90,
		'type1': 'electric',
		'type2': ''
	},
	{
		'abilities': '[\'Static\', \'Lightningrod\', \'Surge Surfer\']',
		'hp': 60,
		'name': 'Raichu',
		'pokedex_number': 26,
		'sp_attack': 95,
		'sp_defense': 85,
		'speed': 110,
		'type1': 'electric',
		'type2': 'electric'
	},
	{
		'abilities': '[\'Sand Veil\', \'Sand Rush\', \'Snow Cloak\', \'Slush Rush\']',
		'hp': 50,
		'name': 'Sandshrew',
		'pokedex_number': 27,
		'sp_attack': 10,
		'sp_defense': 35,
		'speed': 40,
		'type1': 'ground',
		'type2': 'ice'
	},
	{
		'abilities': '[\'Sand Veil\', \'Sand Rush\', \'Snow Cloak\', \'Slush Rush\']',
		'hp': 75,
		'name': 'Sandslash',
		'pokedex_number': 28,
		'sp_attack': 25,
		'sp_defense': 65,
		'speed': 65,
		'type1': 'ground',
		'type2': 'ice'
	},
	{
		'abilities': '[\'Poison Point\', \'Rivalry\', \'Hustle\']',
		'hp': 55,
		'name': 'Nidoran♀',
		'pokedex_number': 29,
		'sp_attack': 40,
		'sp_defense': 40,
		'speed': 41,
		'type1': 'poison',
		'type2': ''
	},
	{
		'abilities': '[\'Poison Point\', \'Rivalry\', \'Hustle\']',
		'hp': 70,
		'name': 'Nidorina',
		'pokedex_number': 30,
		'sp_attack': 55,
		'sp_defense': 55,
		'speed': 56,
		'type1': 'poison',
		'type2': ''
	},
	{
		'abilities': '[\'Poison Point\', \'Rivalry\', \'Sheer Force\']',
		'hp': 90,
		'name': 'Nidoqueen',
		'pokedex_number': 31,
		'sp_attack': 75,
		'sp_defense': 85,
		'speed': 76,
		'type1': 'poison',
		'type2': 'ground'
	},
	{
		'abilities': '[\'Poison Point\', \'Rivalry\', \'Hustle\']',
		'hp': 46,
		'name': 'Nidoran♂',
		'pokedex_number': 32,
		'sp_attack': 40,
		'sp_defense': 40,
		'speed': 50,
		'type1': 'poison',
		'type2': ''
	},
	{
		'abilities': '[\'Poison Point\', \'Rivalry\', \'Hustle\']',
		'hp': 61,
		'name': 'Nidorino',
		'pokedex_number': 33,
		'sp_attack': 55,
		'sp_defense': 55,
		'speed': 65,
		'type1': 'poison',
		'type2': ''
	},
	{
		'abilities': '[\'Poison Point\', \'Rivalry\', \'Sheer Force\']',
		'hp': 81,
		'name': 'Nidoking',
		'pokedex_number': 34,
		'sp_attack': 85,
		'sp_defense': 75,
		'speed': 85,
		'type1': 'poison',
		'type2': 'ground'
	},
	{
		'abilities': '[\'Cute Charm\', \'Magic Guard\', \'Friend Guard\']',
		'hp': 70,
		'name': 'Clefairy',
		'pokedex_number': 35,
		'sp_attack': 60,
		'sp_defense': 65,
		'speed': 35,
		'type1': 'fairy',
		'type2': ''
	},
	{
		'abilities': '[\'Cute Charm\', \'Magic Guard\', \'Unaware\']',
		'hp': 95,
		'name': 'Clefable',
		'pokedex_number': 36,
		'sp_attack': 95,
		'sp_defense': 90,
		'speed': 60,
		'type1': 'fairy',
		'type2': ''
	},
	{
		'abilities': '[\'Flash Fire\', \'Drought\', \'Snow Cloak\', \'Snow Warning\']',
		'hp': 38,
		'name': 'Vulpix',
		'pokedex_number': 37,
		'sp_attack': 50,
		'sp_defense': 65,
		'speed': 65,
		'type1': 'fire',
		'type2': 'ice'
	},
	{
		'abilities': '[\'Flash Fire\', \'Drought\', \'Snow Cloak\', \'Snow Warning\']',
		'hp': 73,
		'name': 'Ninetales',
		'pokedex_number': 38,
		'sp_attack': 81,
		'sp_defense': 100,
		'speed': 109,
		'type1': 'fire',
		'type2': 'ice'
	},
	{
		'abilities': '[\'Cute Charm\', \'Competitive\', \'Friend Guard\']',
		'hp': 115,
		'name': 'Jigglypuff',
		'pokedex_number': 39,
		'sp_attack': 45,
		'sp_defense': 25,
		'speed': 20,
		'type1': 'normal',
		'type2': 'fairy'
	},
	{
		'abilities': '[\'Cute Charm\', \'Competitive\', \'Frisk\']',
		'hp': 140,
		'name': 'Wigglytuff',
		'pokedex_number': 40,
		'sp_attack': 85,
		'sp_defense': 50,
		'speed': 45,
		'type1': 'normal',
		'type2': 'fairy'
	},
	{
		'abilities': '[\'Inner Focus\', \'Infiltrator\']',
		'hp': 40,
		'name': 'Zubat',
		'pokedex_number': 41,
		'sp_attack': 30,
		'sp_defense': 40,
		'speed': 55,
		'type1': 'poison',
		'type2': 'flying'
	},
	{
		'abilities': '[\'Inner Focus\', \'Infiltrator\']',
		'hp': 75,
		'name': 'Golbat',
		'pokedex_number': 42,
		'sp_attack': 65,
		'sp_defense': 75,
		'speed': 90,
		'type1': 'poison',
		'type2': 'flying'
	},
	{
		'abilities': '[\'Chlorophyll\', \'Run Away\']',
		'hp': 45,
		'name': 'Oddish',
		'pokedex_number': 43,
		'sp_attack': 75,
		'sp_defense': 65,
		'speed': 30,
		'type1': 'grass',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Chlorophyll\', \'Stench\']',
		'hp': 60,
		'name': 'Gloom',
		'pokedex_number': 44,
		'sp_attack': 85,
		'sp_defense': 75,
		'speed': 40,
		'type1': 'grass',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Chlorophyll\', \'Effect Spore\']',
		'hp': 75,
		'name': 'Vileplume',
		'pokedex_number': 45,
		'sp_attack': 110,
		'sp_defense': 90,
		'speed': 50,
		'type1': 'grass',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Effect Spore\', \'Dry Skin\', \'Damp\']',
		'hp': 35,
		'name': 'Paras',
		'pokedex_number': 46,
		'sp_attack': 45,
		'sp_defense': 55,
		'speed': 25,
		'type1': 'bug',
		'type2': 'grass'
	},
	{
		'abilities': '[\'Effect Spore\', \'Dry Skin\', \'Damp\']',
		'hp': 60,
		'name': 'Parasect',
		'pokedex_number': 47,
		'sp_attack': 60,
		'sp_defense': 80,
		'speed': 30,
		'type1': 'bug',
		'type2': 'grass'
	},
	{
		'abilities': '[\'Compoundeyes\', \'Tinted Lens\', \'Run Away\']',
		'hp': 60,
		'name': 'Venonat',
		'pokedex_number': 48,
		'sp_attack': 40,
		'sp_defense': 55,
		'speed': 45,
		'type1': 'bug',
		'type2': 'poison'
	},
	{
		'abilities': '[\'Shield Dust\', \'Tinted Lens\', \'Wonder Skin \']',
		'hp': 70,
		'name': 'Venomoth',
		'pokedex_number': 49,
		'sp_attack': 90,
		'sp_defense': 75,
		'speed': 90,
		'type1': 'bug',
		'type2': 'poison'
	}
]

// Return all pokemons
export const pokemons$ = new Promise((resolve, reject) => setTimeout(resolve, 200, pokemons))